version: '2'

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  limesurvey:
    build: .
    links:
      - mysql
    volumes:
      - upload:/app/upload

volumes:
  mysql:
  upload:
