version: '2'

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  limesurvey:
    depends_on:
      - mysql
    volumes:
      - upload:/app/upload
    build: .

volumes:
  mysql:
  upload:
